### ISSUE TITLE
Automated GenBank ingest failing 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#475]
Automated GenBank ingest failures
- https://github.com/nextstrain/ncov-ingest/actions/runs/10817236034
- https://github.com/nextstrain/ncov-ingest/actions/runs/10836359393

Both workflows failed [during transform-rki-data-to-ndjson](https://github.com/nextstrain/ncov-ingest/actions/runs/10836359393/job/30069988588#step:5:704). This is due to upstream changes in the RKI data. RKI announced in https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/59 that some variables have been renamed. This particular error comes from `SEQUENCE.ID` being renamed to `igs_id`, but we use other columns as well.

The [available variables](https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland?tab=readme-ov-file#variablen-und-werte) are listed in the top level README

## TODOs
- [x] update `RKI_INDEX_COL` in [bin/transform-rki-data-to-ndjson](https://github.com/nextstrain/ncov-ingest/blob/a17a6932d7053282d07babed05e3379d87ed7dd5/bin/transform-rki-data-to-ndjson#L8)
- [x] update `COLUMN_MAP` in [bin/transform-rki](https://github.com/nextstrain/ncov-ingest/blob/a17a6932d7053282d07babed05e3379d87ed7dd5/bin/transform-rki#L31-L38)
- [x] add new date format `%Y-%m-%dT%H:%M:%S` to [expected `date_formats`](https://github.com/nextstrain/ncov-ingest/blob/a17a6932d7053282d07babed05e3379d87ed7dd5/lib/utils/transformpipeline/transforms.py#L302)
- [x] parse new JSON blob for pango_lineage
- [ ] diff with old version on S3 (s3://nextstrain-data/files/ncov/rki/metadata.tsv.zst)

**Comment by joverlee521** [comment]
RKI announced in https://github.com/robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland/issues/59 that some variables have been renamed. This particular error comes from `SEQUENCE.ID` being renamed to `igs_id`, but we should verify other [columns that are used in transform-rki](https://github.com/nextstrain/ncov-ingest/blob/a17a6932d7053282d07babed05e3379d87ed7dd5/bin/transform-rki#L31-L38)
