### ISSUE TITLE
Update links for GISAID and GenBank accessions

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov-ingest#484]
_requested by @trvrb on [Slack](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1734046576334539)_

Link between GISAID and GenBank accessions currently come from https://github.com/nextstrain/ncov-ingest/blob/master/source-data/accessions.tsv.gz which was kindly updated by @AngieHinrichs during the pandemic 🙏 

We haven't picked up the task of updating the file, but the links are now maintained at https://hgwdev.gi.ucsc.edu/~angie/epiToPublicAndDate.latest

## TODOs

- [x] download the public accessions file
- [x] replace the manually curated accessions.tsv.gz with the downloaded file
- [x] remove accessions.tsv.gz
